accounts:
  - name: "account1"
    api_key: "your_api_key_here"
    api_secret: "your_api_secret_here"
  - name: "account2"
    api_key: "your_api_key_here"
    api_secret: "your_api_secret_here"

symbols:
  spot:
    - symbol: "BTCUSDT"
    - symbol: "ETHUSDT"
    - symbol: "USDCUSDT"
  perp:
    - symbol: "BTCUSDT"
    - symbol: "ETHUSDT"


